### ISSUE TITLE
CSS : Neumorphic Buttons

### ISSUE THREAD

**Issue by crew-guy** [30-seconds/30-seconds-of-css#205] opened 2020-10-09 07:12 UTC
A simple text-shadow and hover manipulation to get really cool looking design buttons

---

![Neumorphic Design](https://codemyui.com/wp-content/uploads/2020/02/Neumorphic-Button-Click-Hover-and-Clicked-Design.gif)

**Comment by Chalarangelo** [comment] 2020-10-09 09:10
Duplicate of #203

**Closed by Chalarangelo** 2020-10-09 09:10 UTC

**Comment by crew-guy** [comment] 2020-10-09 12:35
Oh wait so so sorry. Completely forgot I had already done this.

### So am I authorized to work on this or not ?
