### ISSUE TITLE
[BUG] Sidebar navigation doesn't seem to work

### ISSUE THREAD

**Issue by fejes713** [30-seconds/30-seconds-of-css#106] opened 2018-10-08 18:35 UTC
Sidebar used to be scrollable, now it doesn't work. Does anyone have similar issues, if so do you have any idea why is that happening? 

Environment: 
MacOS Mojave & Chrome 69.0.3

**Comment by Chalarangelo** [comment] 2018-10-08 18:39
I cannot confirm this, works fine on Firefox 63.0b12/Windows 10.

**Comment by fejes713** [comment] 2018-10-08 18:45
Confirmed. Works on my Firefox as well. Might be a bug with Chrome version I am using right now.

**Comment by Chalarangelo** [comment] 2018-10-08 18:47
Works on Chrome 69.0.3497.100/Windows 10 for me. But I see what appears to be a custom scrollbar in the navigation panel, could that be causing the issue?

**Comment by flxwu** [comment] 2018-10-08 18:56
Works for me on Chrome 71 aswell

**Comment by skatcat31** [comment] 2018-10-08 21:36
I cannot recreate this issue and it seems local. @fejes713 can you confirm what version you're on for Chrome and then update and try again with version confirmation?

This way we might be able to get an old canary build or just note it.

**Comment by Chalarangelo** [comment] 2019-01-12 11:19
Been a while, nobody is talking about this. I think it's safe to say it's not a generalized issue and it's not easily reproducible, so I'm closing this for now. Feel free to reopen if you manage to reproduce this and share the info with the rest of us.

**Closed by Chalarangelo** 2019-01-12 11:19 UTC
